plugins {
    id 'application'
}

group = 'com.tomsunsoya'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    mainClass = 'Main'
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
            exclude 'assets/**'
        }
        resources {
            srcDirs = ['src']
            include 'assets/**'
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
